version: '3.8'

services:

  mongoDB:
    image: mongo
    container_name: mongo-docker-dices-api
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db

volumes:
      database-data:
        external: true

  
    