name: Build

on: 
  push:
    branches: [master, main, docker]
  pull_request:
    branches: [master, main, docker]
    
    

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
          
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci
      - run: npm install --save-dev jest
      - run: npm install --save-dev supertest

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test